const { GoogleGenerativeAI } = require('@google/generative-ai');

// Smart mock response for demo mode (when no Gemini key)
const getMockAnalysis = (description) => {
  const lower = (description || '').toLowerCase();
  let category = 'Handmade';
  let subcategory = 'Artisan Products';
  let material = 'Cotton';
  let style = 'Traditional';
  let tags = ['handmade', 'artisan', 'india'];
  let priceMin = 500, priceMax = 1500, suggested = 999;

  if (lower.includes('saree') || lower.includes('sari')) {
    category = 'Sarees'; subcategory = 'Handwoven Sarees';
    material = 'Silk/Cotton'; style = 'Traditional Indian';
    tags = ['saree', 'handloom', 'traditional', 'indian', 'women'];
    priceMin = 1200; priceMax = 5000; suggested = 2499;
  } else if (lower.includes('kurta')) {
    category = "Men's Fashion"; subcategory = 'Kurtas';
    material = 'Cotton'; style = 'Ethnic';
    tags = ['kurta', 'ethnic', 'handmade', 'indian'];
    priceMin = 400; priceMax = 1500; suggested = 799;
  } else if (lower.includes('shawl') || lower.includes('dupatta')) {
    category = 'Handloom'; subcategory = 'Shawls';
    material = 'Wool/Pashmina'; style = 'Traditional';
    tags = ['shawl', 'handloom', 'warm', 'traditional'];
    priceMin = 800; priceMax = 3000; suggested = 1499;
  } else if (lower.includes('bag') || lower.includes('purse')) {
    category = 'Accessories'; subcategory = 'Bags';
    material = 'Jute/Fabric'; style = 'Handcrafted';
    tags = ['bag', 'handmade', 'eco-friendly', 'artisan'];
    priceMin = 300; priceMax = 1200; suggested = 649;
  } else if (lower.includes('jewelry') || lower.includes('jewellery') || lower.includes('necklace')) {
    category = 'Accessories'; subcategory = 'Jewelry';
    material = 'Silver/Brass'; style = 'Traditional';
    tags = ['jewelry', 'handcrafted', 'traditional', 'indian'];
    priceMin = 500; priceMax = 3000; suggested = 1299;
  } else if (lower.includes('dress') || lower.includes('suit')) {
    category = "Women's Fashion"; subcategory = 'Dresses';
    material = 'Cotton'; style = 'Handmade';
    tags = ['dress', 'handmade', 'women', 'fashion'];
    priceMin = 600; priceMax = 2000; suggested = 1099;
  }

  // Extract a product name from description
  const words = description ? description.split(' ').slice(0, 5).join(' ') : 'Handcrafted Artisan Product';
  const productName = words.charAt(0).toUpperCase() + words.slice(1);

  return {
    product_name: productName,
    description: `A beautifully crafted ${category.toLowerCase()} made by skilled Indian artisans. This ${style.toLowerCase()} piece showcases traditional craftsmanship passed down through generations. Made with high-quality ${material.toLowerCase()}, each piece is unique and reflects the rich cultural heritage of India. Perfect for gifting or personal use, this handmade product supports local artisans and their communities.`,
    category,
    subcategory,
    material,
    style,
    tags,
    color_suggestions: ['Natural', 'Earth Tones', 'Traditional Motifs'],
    price_range: { min: priceMin, max: priceMax },
    suggested_price: suggested,
    ai_notes: 'Generated by KalaStyle AI � prices are suggested estimates. Adjust based on your actual costs and market rates.'
  };
};

// POST /api/ai/analyze-product
exports.analyzeProduct = async (req, res) => {
  try {
    const { image_url, description } = req.body;

    if (!description && !image_url) {
      return res.status(400).json({ error: 'Please provide an image or description' });
    }

    const geminiKey = process.env.GEMINI_API_KEY;

    // If no Gemini key, use smart mock
    if (!geminiKey || geminiKey === 'YOUR_GEMINI_API_KEY') {
      console.log('??  No Gemini API key � using demo mock response');
      await new Promise(r => setTimeout(r, 2000)); // simulate AI delay
      return res.json(getMockAnalysis(description));
    }

    // Real Gemini API call
    const genAI = new GoogleGenerativeAI(geminiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    const prompt = `You are an expert e-commerce product listing assistant for KalaStyle AI, a marketplace for Indian artisans.

Analyze this artisan product and return a JSON object with these exact fields:
- product_name: string (concise, marketable name)
- description: string (professional e-commerce description, 3-4 sentences)
- category: string (one of: Sarees, Men's Fashion, Women's Fashion, Handloom, Handmade, Accessories)
- subcategory: string
- material: string
- style: string
- tags: array of 5-8 relevant search tags
- color_suggestions: array of color names
- price_range: { min: number, max: number } in Indian Rupees
- suggested_price: number in Indian Rupees
- ai_notes: brief note about pricing

Artisan's description: "${description || 'No description provided'}"

Respond with ONLY valid JSON, no markdown, no explanation.`;

    const parts = [{ text: prompt }];

    // If image provided, add it
    if (image_url) {
      try {
        const imageRes = await fetch(image_url);
        const imageBuffer = await imageRes.arrayBuffer();
        const base64 = Buffer.from(imageBuffer).toString('base64');
        const mimeType = imageRes.headers.get('content-type') || 'image/jpeg';
        parts.push({ inlineData: { mimeType, data: base64 } });
      } catch (imgErr) {
        console.warn('Could not fetch image for analysis:', imgErr.message);
      }
    }

    const result = await model.generateContent(parts);
    const text = result.response.text().trim();
    
    // Clean JSON response
    const jsonStr = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const parsed = JSON.parse(jsonStr);

    res.json(parsed);
  } catch (err) {
    console.error('AI analyze error:', err);
    // Fallback to mock on any error
    res.json(getMockAnalysis(req.body.description));
  }
};

// POST /api/ai/generate-description
exports.generateDescription = async (req, res) => {
  try {
    const { simple_text, language = 'English' } = req.body;
    if (!simple_text) {
      return res.status(400).json({ error: 'Please provide simple_text' });
    }

    const geminiKey = process.env.GEMINI_API_KEY;
    if (!geminiKey || geminiKey === 'YOUR_GEMINI_API_KEY') {
      await new Promise(r => setTimeout(r, 1000));
      return res.json({
        professional_description: `A beautifully handcrafted piece made with love and skill by Indian artisans. ${simple_text}. Each item is unique, reflecting the rich tradition of Indian craftsmanship. This product makes a perfect gift and supports local artisan communities.`
      });
    }

    const genAI = new GoogleGenerativeAI(geminiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    const prompt = `Convert this simple artisan product description into a professional, attractive e-commerce product description in ${language}.

Simple description: "${simple_text}"

Write 3-4 sentences that highlight:
1. The craftsmanship and authenticity
2. The material and quality
3. The cultural heritage
4. Why a customer should buy it

Return ONLY the description text, nothing else.`;

    const result = await model.generateContent(prompt);
    res.json({ professional_description: result.response.text().trim() });
  } catch (err) {
    console.error('AI generate description error:', err);
    res.json({
      professional_description: `A beautifully handcrafted product made with care by skilled Indian artisans. ${req.body.simple_text}. Each piece carries the rich heritage of Indian craftsmanship and is made with quality materials.`
    });
  }
};
